/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.SchoolTracker;
import java.awt.*;
import javax.swing.*;
import java.awt.event.*;
import java.util.Calendar;
import java.io.*;
import java.util.ArrayList;
/**
 *
 * @author Kyle
 */
public class TrackerCardGUI extends javax.swing.JFrame {

    private Student newStudent;
    private CourseOffering newCourseOffering;
    private Category newCategory;
    private Assignment newAssignment;
    /**
     * Creates new form TrackerCardGUI
     */
    public TrackerCardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        addStudentButton = new javax.swing.JButton();
        loadStudentButton = new javax.swing.JButton();
        newStudentPanel = new javax.swing.JPanel();
        newStudentNameField = new javax.swing.JTextField();
        newStudentIdField = new javax.swing.JTextField();
        newStudentEarnedField = new javax.swing.JTextField();
        newStudentNeededField = new javax.swing.JTextField();
        createStudentButton = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        newStudentTextArea = new javax.swing.JTextArea();
        loadStudentPanel = new javax.swing.JPanel();
        loadStudentInfoLabel = new javax.swing.JLabel();
        loadStudentIdField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        mainCoursePanel = new javax.swing.JPanel();
        viewCoursesButton = new javax.swing.JButton();
        addCourseButton = new javax.swing.JButton();
        nameLabel = new javax.swing.JLabel();
        addCoursesPanel = new javax.swing.JPanel();
        newCourseNameField = new javax.swing.JTextField();
        newCoursePrefixField = new javax.swing.JTextField();
        newCourseCodeField = new javax.swing.JTextField();
        newCourseGradeField = new javax.swing.JTextField();
        newCourseCreditsField = new javax.swing.JTextField();
        newCourseNextButton = new javax.swing.JButton();
        newCourseGradeCombo = new javax.swing.JComboBox<>();
        newCourseFinishedCheck = new javax.swing.JCheckBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        addCategoryPanel = new javax.swing.JPanel();
        addCategoryFinishButton = new javax.swing.JButton();
        addCategoryInfoLabel = new javax.swing.JLabel();
        addCategoryNameField = new javax.swing.JTextField();
        addCategoryWeightField = new javax.swing.JTextField();
        addCategoryAddButton = new javax.swing.JButton();
        viewCoursesPanel = new javax.swing.JPanel();
        studentCardButton = new javax.swing.JButton();
        courseCardButton = new javax.swing.JButton();
        infoCardButton = new javax.swing.JButton();
        saveProgressButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course Tracker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        mainPanel.setLayout(new java.awt.CardLayout());

        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        loadStudentButton.setText("Load Student");
        loadStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanelLayout.createSequentialGroup()
                .addContainerGap(176, Short.MAX_VALUE)
                .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(loadStudentButton)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(162, 162, 162))
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );

        mainPanel.add(defaultPanel, "defaultPanel");

        newStudentNameField.setText("Name");
        newStudentNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentNameFieldFocusGained(evt);
            }
        });
        newStudentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentNameFieldActionPerformed(evt);
            }
        });

        newStudentIdField.setText("ID");
        newStudentIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentIdFieldFocusGained(evt);
            }
        });
        newStudentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentIdFieldActionPerformed(evt);
            }
        });

        newStudentEarnedField.setText("Credits Earned");
        newStudentEarnedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentEarnedFieldFocusGained(evt);
            }
        });

        newStudentNeededField.setText("Credits Needed");
        newStudentNeededField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentNeededFieldFocusGained(evt);
            }
        });

        createStudentButton.setText("Create Student");
        createStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentButtonActionPerformed(evt);
            }
        });

        newStudentTextArea.setColumns(20);
        newStudentTextArea.setRows(5);
        newStudentTextArea.setText("Please enter your information.\n"
            + "If you have existing credits please only enter\n"
            + "the credits that will not effect your GPA.\n"
            + "If no existing credits, enter 0.");
        jScrollPane2.setViewportView(newStudentTextArea);

        javax.swing.GroupLayout newStudentPanelLayout = new javax.swing.GroupLayout(newStudentPanel);
        newStudentPanel.setLayout(newStudentPanelLayout);
        newStudentPanelLayout.setHorizontalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addGap(71, 71, 71)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStudentPanelLayout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 296, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(newStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newStudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                        .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newStudentNeededField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(newStudentEarnedField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(91, 91, 91))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, newStudentPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(createStudentButton)
                .addGap(161, 161, 161))
        );
        newStudentPanelLayout.setVerticalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(53, 53, 53)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentEarnedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudentNeededField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(createStudentButton)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        mainPanel.add(newStudentPanel, "newStudentPanel");

        loadStudentInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadStudentInfoLabel.setText("Enter student ID");

        loadButton.setText("Load");
        loadButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout loadStudentPanelLayout = new javax.swing.GroupLayout(loadStudentPanel);
        loadStudentPanel.setLayout(loadStudentPanelLayout);
        loadStudentPanelLayout.setHorizontalGroup(
            loadStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadStudentPanelLayout.createSequentialGroup()
                .addContainerGap(185, Short.MAX_VALUE)
                .addGroup(loadStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(loadStudentInfoLabel)
                    .addComponent(loadStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(loadButton, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(170, 170, 170))
        );
        loadStudentPanelLayout.setVerticalGroup(
            loadStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadStudentPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loadStudentInfoLabel)
                .addGap(18, 18, 18)
                .addComponent(loadStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadButton)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        mainPanel.add(loadStudentPanel, "loadStudentPanel");

        mainCoursePanel.setName(""); // NOI18N

        viewCoursesButton.setText("View Courses");
        viewCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoursesButtonActionPerformed(evt);
            }
        });

        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainCoursePanelLayout = new javax.swing.GroupLayout(mainCoursePanel);
        mainCoursePanel.setLayout(mainCoursePanelLayout);
        mainCoursePanelLayout.setHorizontalGroup(
            mainCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCoursePanelLayout.createSequentialGroup()
                .addGap(178, 178, 178)
                .addComponent(nameLabel)
                .addContainerGap(257, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCoursePanelLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(mainCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(addCourseButton, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(viewCoursesButton))
                .addGap(168, 168, 168))
        );
        mainCoursePanelLayout.setVerticalGroup(
            mainCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCoursePanelLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(nameLabel)
                .addGap(32, 32, 32)
                .addComponent(viewCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );

        mainPanel.add(mainCoursePanel, "mainCoursePanel");

        newCourseNameField.setText("Name");
        newCourseNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseNameFieldFocusGained(evt);
            }
        });

        newCoursePrefixField.setText("Prefix");
        newCoursePrefixField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCoursePrefixFieldFocusGained(evt);
            }
        });

        newCourseCodeField.setText("Code");
        newCourseCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseCodeFieldFocusGained(evt);
            }
        });

        newCourseGradeField.setText("Grade");
        newCourseGradeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseGradeFieldFocusGained(evt);
            }
        });

        newCourseCreditsField.setText("Credits");
        newCourseCreditsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseCreditsFieldFocusGained(evt);
            }
        });

        newCourseNextButton.setText("Next");
        newCourseNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseNextButtonActionPerformed(evt);
            }
        });

        newCourseGradeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classic", "Pass Fail" }));

        newCourseFinishedCheck.setText("Course Finished");

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("Please enter the course information.\n" + "If the course is a pass/fall type of course\n" + "enter grade as a 0 for fail and a 1 for pass.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout addCoursesPanelLayout = new javax.swing.GroupLayout(addCoursesPanel);
        addCoursesPanel.setLayout(addCoursesPanelLayout);
        addCoursesPanelLayout.setHorizontalGroup(
            addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(newCourseCodeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newCoursePrefixField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newCourseGradeCombo, 0, 100, Short.MAX_VALUE))
                            .addComponent(newCourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 137, Short.MAX_VALUE)
                        .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(newCourseGradeField)
                                .addComponent(newCourseCreditsField, javax.swing.GroupLayout.DEFAULT_SIZE, 114, Short.MAX_VALUE))
                            .addComponent(newCourseFinishedCheck)
                            .addComponent(newCourseNextButton)))
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addGap(0, 71, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 285, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(74, 74, 74))
        );
        addCoursesPanelLayout.setVerticalGroup(
            addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoursesPanelLayout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(newCourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newCoursePrefixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCourseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newCourseGradeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(newCourseFinishedCheck)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newCourseGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(newCourseCreditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(newCourseNextButton)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        mainPanel.add(addCoursesPanel, "addCoursesPanel");

        addCategoryFinishButton.setText("Finish");
        addCategoryFinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCatagoryFinishButtonActionPerformed(evt);
            }
        });

        addCategoryInfoLabel.setText("Add a catagory");

        addCategoryNameField.setText("Catagory Name");
        addCategoryNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addCategoryNameFieldFocusGained(evt);
            }
        });

        addCategoryWeightField.setText("Weight");
        addCategoryWeightField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addCategoryWeightFieldFocusGained(evt);
            }
        });

        addCategoryAddButton.setText("add");
        addCategoryAddButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCategoryAddButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCategoryPanelLayout = new javax.swing.GroupLayout(addCategoryPanel);
        addCategoryPanel.setLayout(addCategoryPanelLayout);
        addCategoryPanelLayout.setHorizontalGroup(
            addCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCategoryPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(addCategoryInfoLabel)
                .addGap(180, 180, 180))
            .addGroup(addCategoryPanelLayout.createSequentialGroup()
                .addGroup(addCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCategoryPanelLayout.createSequentialGroup()
                        .addGap(87, 87, 87)
                        .addComponent(addCategoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCategoryWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(addCategoryAddButton))
                    .addGroup(addCategoryPanelLayout.createSequentialGroup()
                        .addGap(186, 186, 186)
                        .addComponent(addCategoryFinishButton)))
                .addContainerGap(89, Short.MAX_VALUE))
        );
        addCategoryPanelLayout.setVerticalGroup(
            addCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCategoryPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addCategoryInfoLabel)
                .addGap(60, 60, 60)
                .addGroup(addCategoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(addCategoryNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryWeightField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addCategoryAddButton))
                .addGap(18, 18, 18)
                .addComponent(addCategoryFinishButton)
                .addContainerGap(86, Short.MAX_VALUE))
        );

        mainPanel.add(addCategoryPanel, "addCategoryPanel");

        viewCoursesPanel.setPreferredSize(new java.awt.Dimension(402, 229));
        viewCoursesPanel.setRequestFocusEnabled(false);
        mainPanel.add(viewCoursesPanel, "viewCoursesPanel");

        studentCardButton.setText("Student");
        studentCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCardButtonActionPerformed(evt);
            }
        });

        courseCardButton.setText("Courses");
        courseCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCardButtonActionPerformed(evt);
            }
        });

        infoCardButton.setText("Info");

        saveProgressButton.setText("Save Progress");
        saveProgressButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveProgressButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(saveProgressButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 28, Short.MAX_VALUE)
                .addComponent(studentCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(courseCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(infoCardButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(314, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentCardButton)
                    .addComponent(courseCardButton)
                    .addComponent(infoCardButton)
                    .addComponent(saveProgressButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(68, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCardButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "defaultPanel");
    }//GEN-LAST:event_studentCardButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "newStudentPanel");
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void loadStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStudentButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loadStudentPanel");
    }//GEN-LAST:event_loadStudentButtonActionPerformed

    private void newStudentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudentNameFieldActionPerformed

    private void newStudentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudentIdFieldActionPerformed

    private void createStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentButtonActionPerformed
        try{
            newStudent = new Student(newStudentNameField.getText(),
                Integer.parseInt(newStudentIdField.getText()),
                    Integer.parseInt(newStudentNeededField.getText()));
        
            //newStudent.setCreditsEarned(Integer.parseInt(newStudentEarnedField.getText()));
            //newStudent.setGpa(Double.parseDouble(newStudentGpaField.getText()));
        
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "mainCoursePanel");
            nameLabel.setText("Hello, " + newStudent.getName());
        
            System.out.println(newStudent);
            
            saveStudent(newStudent);
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null,
                "Please enter numbers for ID, GPA, Credits Earned, and Credits Needed",
                    "Student warning", JOptionPane.WARNING_MESSAGE);
        }catch (NullPointerException e){
            ;
        }
        
    }//GEN-LAST:event_createStudentButtonActionPerformed

    private void newStudentNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentNameFieldFocusGained
        newStudentNameField.setText("");
    }//GEN-LAST:event_newStudentNameFieldFocusGained

    private void newStudentIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentIdFieldFocusGained
        newStudentIdField.setText("");
    }//GEN-LAST:event_newStudentIdFieldFocusGained

    private void newStudentEarnedFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentEarnedFieldFocusGained
        newStudentEarnedField.setText("");
    }//GEN-LAST:event_newStudentEarnedFieldFocusGained

    private void newStudentNeededFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentNeededFieldFocusGained
        newStudentNeededField.setText("");
    }//GEN-LAST:event_newStudentNeededFieldFocusGained

    private void courseCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCardButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainCoursePanel");
    }//GEN-LAST:event_courseCardButtonActionPerformed

    private void viewCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoursesButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "viewCoursesPanel");
    }//GEN-LAST:event_viewCoursesButtonActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addCoursesPanel");
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void viewCourseActionPerformed(ActionEvent event)
    {
        JButton button = (JButton) event.getSource();
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, button.getText());
        
        currentCourse = button.getText();   
    }
    
    private void createAssignmentActionPerformed(ActionEvent event)
    {
           CardLayout card  = (CardLayout) mainPanel.getLayout();
           card.show(mainPanel, currentCourse + " assignmentPanel");
    }
    private void newCourseNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseNameFieldFocusGained
        newCourseNameField.setText("");
    }//GEN-LAST:event_newCourseNameFieldFocusGained

    private void newCoursePrefixFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCoursePrefixFieldFocusGained
        newCoursePrefixField.setText("");
    }//GEN-LAST:event_newCoursePrefixFieldFocusGained

    private void newCourseCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseCodeFieldFocusGained
        newCourseCodeField.setText("");
    }//GEN-LAST:event_newCourseCodeFieldFocusGained

    private void newCourseNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseNextButtonActionPerformed
        try{
            Course newCourse = new Course(newCourseNameField.getText(),
                newCoursePrefixField.getText(), Integer.parseInt(newCourseCodeField.getText()),
                    Integer.parseInt(newCourseCreditsField.getText()));
        
            int gradeType = 0;
            String gradeTypeChoice = (String) newCourseGradeCombo.getSelectedItem();
            if (gradeTypeChoice.equals("Classic"))
                gradeType = 0;
            else
                gradeType = 1;
        
            boolean isFinished;
            if (newCourseFinishedCheck.isSelected())
                isFinished = true;
            else
                isFinished = false;
        
            newCourseOffering = new CourseOffering(newCourse, gradeType,
                isFinished, Double.parseDouble(newCourseGradeField.getText()));
        
            newStudent.addCourse(newCourseOffering);
            System.out.println(newStudent);
        
            CardLayout card = (CardLayout)mainPanel.getLayout();
            card.show(mainPanel, "addCategoryPanel");
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,
                "Enter a number for Code, Grade, and Credits", "Creation warning",
                        JOptionPane.WARNING_MESSAGE);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,
                "You must first create or load a student.", "Creation warning",
                        JOptionPane.WARNING_MESSAGE);
        }
        
        String course = newCourseNameField.getText();
        JButton newButton = new JButton(course);
        
        
        CardLayout card = (CardLayout) mainPanel.getLayout();
        viewCoursesPanel.add(newButton);
        newButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                viewCourseActionPerformed(evt); 
            }
        }
        );
        
        JPanel newPanel = new JPanel();
        newPanel.setLayout(new BorderLayout());
        
        JLabel newLabel = new JLabel(course);
        JPanel assignmentListPanel = new JPanel();
        assignmentListPanel.setLayout(new FlowLayout());
        JButton assignmentButton = new JButton("Add Assignment");
        assignmentButton.addActionListener(new ActionListener()
        {
            public void actionPerformed (ActionEvent event)
            {
                createAssignmentActionPerformed(event);
            }
        }
        );
        newPanel.add(newLabel, BorderLayout.NORTH);
        newPanel.add(assignmentListPanel, BorderLayout.CENTER);
        newPanel.add(assignmentButton, BorderLayout.SOUTH);
        
        
        addAssignmentPanel = new JPanel();
        assignmentName = new JTextField("Assignment Name");
        assignmentGrade = new JTextField("Assignment Grade");
        addAssignment = new JButton("Add");
        categories = new ButtonGroup();
        addAssignment.addActionListener(new ActionListener() 
        {
            public void actionPerformed(ActionEvent event)
            {
                addAssignmentButtonActionPerformed(event);
            }
        }
        );
        
        addAssignmentPanel.add(assignmentName);
        addAssignmentPanel.add(assignmentGrade);
        addAssignmentPanel.add(addAssignment);
        
        mainPanel.add(newPanel, course);
        mainPanel.add(addAssignmentPanel, course + " assignmentPanel");
        viewCoursesPanel.revalidate(); 
        
        newCourseNameField.setText("Name");
        newCourseGradeField.setText("Grade");
        newCourseCreditsField.setText("Credits");
        newCourseCodeField.setText("Code");
        newCoursePrefixField.setText("Prefix");
        
    
    
    }//GEN-LAST:event_newCourseNextButtonActionPerformed

    private void addAssignmentButtonActionPerformed(java.awt.event.ActionEvent evt)
    {
        int grade = Integer.parseInt(assignmentGrade.getText());
        Assignment newAssignment = new Assignment(grade, assignmentName.getText());
        JLabel assignmentLabel = new JLabel(newAssignment.getName() + ": " + newAssignment.getGrade());
        
        ButtonModel button = categories.getSelection();
        String newCategory;
        if (button == null)
            System.out.println("Please pick a selection");
        newCategory = button.getActionCommand();
        
        System.out.println(currentCourse);
        CourseOffering course = newStudent.getCourseOffering(currentCourse);
        Category thisCategory = course.getCategory(newCategory);
        thisCategory.addAssignment(newAssignment);
        
        CardLayout card = (CardLayout) mainPanel.getLayout();
        card.show(mainPanel, currentCourse);
        
        JPanel coursePanel = null;
        Component visibleComp = null;
        for (Component comp : mainPanel.getComponents()) 
        {
            if (comp.isVisible()) 
            {
                visibleComp = comp;
                coursePanel = (JPanel) visibleComp;
                break;
            }
        }
        
        coursePanel.add(assignmentLabel);
        coursePanel.revalidate();
    }//GEN-LAST:event_addAssignmentButtonActionPerformed

    private void newCourseGradeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseGradeFieldFocusGained
        newCourseGradeField.setText("");
    }//GEN-LAST:event_newCourseGradeFieldFocusGained

    private void newCourseCreditsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseCreditsFieldFocusGained
        newCourseCreditsField.setText("");
    }//GEN-LAST:event_newCourseCreditsFieldFocusGained

    private void addCatagoryFinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCatagoryFinishButtonActionPerformed
        

    }//GEN-LAST:event_addCatagoryFinishButtonActionPerformed

    private void addCategoryAddButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCategoryAddButtonActionPerformed
        try{
            Category newCategory = new Category(addCategoryNameField.getText(),
            Double.parseDouble(addCategoryWeightField.getText()));
        
            newCourseOffering.addCategory(newCategory);
        
            JRadioButton newButton = new JRadioButton(newCategory.getName());
            categories.add(newButton);
            addAssignmentPanel.add(newButton); 
            addAssignmentPanel.revalidate();
        
            System.out.println(newStudent);
        }catch (NumberFormatException e){
            JOptionPane.showMessageDialog(null,
                "Weight must be a number.", "Category warning",
                        JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_addCategoryAddButtonActionPerformed

    private void saveProgressButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveProgressButtonActionPerformed
        try{
            saveStudent(newStudent);
        }catch (NullPointerException e){
            JOptionPane.showMessageDialog(null,
                "You must first create or load a student.", "Save warning",
                        JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_saveProgressButtonActionPerformed

    private void loadButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadButtonActionPerformed
        loadStudent(loadStudentIdField.getText());
    }//GEN-LAST:event_loadButtonActionPerformed

    private void addCategoryNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addCategoryNameFieldFocusGained
        addCategoryNameField.setText("");
    }//GEN-LAST:event_addCategoryNameFieldFocusGained

    private void addCategoryWeightFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addCategoryWeightFieldFocusGained
        addCategoryWeightField.setText("");
    }//GEN-LAST:event_addCategoryWeightFieldFocusGained

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackerCardGUI().setVisible(true);
            }
        });
    }
    
    public void saveStudent(Student newStudent){
        try{
            FileOutputStream fileOut = 
                    new FileOutputStream("src/project/SchoolTracker/" + newStudent.getId() + ".ser");
            ObjectOutputStream out = new ObjectOutputStream(fileOut);
            out.writeObject(newStudent);
            out.close();
            fileOut.close();
            
            JOptionPane.showMessageDialog(null,
                "Student was saved", "Student Saved",
                        JOptionPane.INFORMATION_MESSAGE);
        }catch (IOException e){
            System.err.println(e);
        }
    }
    
    public void loadStudent(String studentId){
        try{
            FileInputStream fileIn = 
                    new FileInputStream("src/project/SchoolTracker/" + studentId + ".ser");
            ObjectInputStream in = new ObjectInputStream(fileIn);
            newStudent = (Student) in.readObject();
            in.close();
            fileIn.close();
            
            ArrayList<CourseOffering> courses = newStudent.getCourses();
            System.out.println(courses.toString());
            for (int i = 0; i < courses.size(); i++)
            {
                createCoursePanel(courses.get(i));
                ArrayList<Category> categoryList = courses.get(i).getCategories();
                
                for (int j = 0; j < categoryList.size(); j++)
                {
                    createCategory(categoryList.get(j));
                }
            }
            
            
            JOptionPane.showMessageDialog(null,
                "Student was loaded.", "Student Loaded",
                        JOptionPane.INFORMATION_MESSAGE);
            
        }catch (IOException e){
            e.printStackTrace();
            JOptionPane.showMessageDialog(null,
                "Please enter a valid ID number or create a new student.", "Load warning",
                        JOptionPane.WARNING_MESSAGE);
            System.err.println(e);
        }catch (ClassNotFoundException e){
            System.err.println(e);
        }
    }
    
    public void createCoursePanel(CourseOffering course)
    {
        JButton newButton = new JButton(course.getName());
    
        CardLayout card = (CardLayout) mainPanel.getLayout();
        viewCoursesPanel.add(newButton);
        newButton.addActionListener(new ActionListener() 
        {
            public void actionPerformed(java.awt.event.ActionEvent evt) 
            {
                viewCourseActionPerformed(evt); 
            }
        }
        );
        
        JPanel newPanel = new JPanel();
        newPanel.setLayout(new BorderLayout());
        
        JLabel newLabel = new JLabel(course.getName());
        JButton assignmentButton = new JButton("Add Assignment");
        assignmentButton.addActionListener(new ActionListener()
        {
            public void actionPerformed (ActionEvent event)
            {
                createAssignmentActionPerformed(event);
            }
        }
        );
        newPanel.add(newLabel, BorderLayout.NORTH);
        newPanel.add(assignmentButton, BorderLayout.SOUTH);
        
        mainPanel.add(newPanel, course.getName());
        viewCoursesPanel.revalidate();
    }
    
    public void createCategory(Category newCategory)
    {
         JRadioButton newButton = new JRadioButton(newCategory.getName());
         addAssignmentPanel.add(newButton); 
         addAssignmentPanel.revalidate();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCategoryAddButton;
    private javax.swing.JButton addCategoryFinishButton;
    private javax.swing.JLabel addCategoryInfoLabel;
    private javax.swing.JTextField addCategoryNameField;
    private javax.swing.JPanel addCategoryPanel;
    private javax.swing.JTextField addCategoryWeightField;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JPanel addCoursesPanel;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton courseCardButton;
    private javax.swing.JButton createStudentButton;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JButton infoCardButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton loadStudentButton;
    private javax.swing.JTextField loadStudentIdField;
    private javax.swing.JLabel loadStudentInfoLabel;
    private javax.swing.JPanel loadStudentPanel;
    private javax.swing.JPanel mainCoursePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField newCourseCodeField;
    private javax.swing.JTextField newCourseCreditsField;
    private javax.swing.JCheckBox newCourseFinishedCheck;
    private javax.swing.JComboBox<String> newCourseGradeCombo;
    private javax.swing.JTextField newCourseGradeField;
    private javax.swing.JTextField newCourseNameField;
    private javax.swing.JButton newCourseNextButton;
    private javax.swing.JTextField newCoursePrefixField;
    private javax.swing.JTextField newStudentEarnedField;
    private javax.swing.JTextField newStudentIdField;
    private javax.swing.JTextField newStudentNameField;
    private javax.swing.JTextField newStudentNeededField;
    private javax.swing.JPanel newStudentPanel;
    private javax.swing.JTextArea newStudentTextArea;
    private javax.swing.JButton saveProgressButton;
    private javax.swing.JButton studentCardButton;
    private javax.swing.JButton viewCoursesButton;
    private javax.swing.JPanel viewCoursesPanel;
    // End of variables declaration//GEN-END:variables
    private String currentCourse;
    JPanel addAssignmentPanel;
    JTextField assignmentName;
    JTextField assignmentGrade;
    JButton addAssignment;
    ButtonGroup categories;
}
