/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project.SchoolTracker;
import java.awt.*;
import java.util.Calendar;
/**
 *
 * @author Kyle
 */
public class TrackerCardGUI extends javax.swing.JFrame {

    private Student newStudent;
    /**
     * Creates new form TrackerCardGUI
     */
    public TrackerCardGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        defaultPanel = new javax.swing.JPanel();
        addStudentButton = new javax.swing.JButton();
        loadStudentButton = new javax.swing.JButton();
        newStudentPanel = new javax.swing.JPanel();
        newStudentInfoLabel = new javax.swing.JLabel();
        newStudentNameField = new javax.swing.JTextField();
        newStudentIdField = new javax.swing.JTextField();
        newStudentGpaField = new javax.swing.JTextField();
        newStudentEarnedField = new javax.swing.JTextField();
        newStudentNeededField = new javax.swing.JTextField();
        createStudentButton = new javax.swing.JButton();
        loadStudentPanel = new javax.swing.JPanel();
        loadStudentInfoLabel = new javax.swing.JLabel();
        loadStudentIdField = new javax.swing.JTextField();
        loadButton = new javax.swing.JButton();
        mainCoursePanel = new javax.swing.JPanel();
        viewCoursesButton = new javax.swing.JButton();
        addCourseButton = new javax.swing.JButton();
        addCoursesPanel = new javax.swing.JPanel();
        newCourseInfoLabel = new javax.swing.JLabel();
        newCourseNameField = new javax.swing.JTextField();
        newCoursePrefixField = new javax.swing.JTextField();
        newCourseCodeField = new javax.swing.JTextField();
        newCourseStartField = new javax.swing.JTextField();
        newCourseEndField = new javax.swing.JTextField();
        newCourseGradeField = new javax.swing.JTextField();
        newCourseCreditsField = new javax.swing.JTextField();
        newCourseNextButton = new javax.swing.JButton();
        newCourseGradeCombo = new javax.swing.JComboBox<>();
        newCourseFinishedCheck = new javax.swing.JCheckBox();
        addCatagoryPanel = new javax.swing.JPanel();
        addCatagoryFinishButton = new javax.swing.JButton();
        viewCoursesPanel = new javax.swing.JPanel();
        studentCardButton = new javax.swing.JButton();
        courseCardButton = new javax.swing.JButton();
        calculatorCardButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Course Tracker");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setLocation(new java.awt.Point(0, 0));

        mainPanel.setLayout(new java.awt.CardLayout());

        addStudentButton.setText("Add Student");
        addStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addStudentButtonActionPerformed(evt);
            }
        });

        loadStudentButton.setText("Load Student");
        loadStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loadStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout defaultPanelLayout = new javax.swing.GroupLayout(defaultPanel);
        defaultPanel.setLayout(defaultPanelLayout);
        defaultPanelLayout.setHorizontalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(defaultPanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        defaultPanelLayout.setVerticalGroup(
            defaultPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, defaultPanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(addStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(loadStudentButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );

        mainPanel.add(defaultPanel, "defaultPanel");

        newStudentInfoLabel.setText("Enter student information");

        newStudentNameField.setText("Name");
        newStudentNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentNameFieldFocusGained(evt);
            }
        });
        newStudentNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentNameFieldActionPerformed(evt);
            }
        });

        newStudentIdField.setText("ID");
        newStudentIdField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentIdFieldFocusGained(evt);
            }
        });
        newStudentIdField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newStudentIdFieldActionPerformed(evt);
            }
        });

        newStudentGpaField.setText("GPA");
        newStudentGpaField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentGpaFieldFocusGained(evt);
            }
        });

        newStudentEarnedField.setText("Credits Earned");
        newStudentEarnedField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentEarnedFieldFocusGained(evt);
            }
        });

        newStudentNeededField.setText("Credits Needed");
        newStudentNeededField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newStudentNeededFieldFocusGained(evt);
            }
        });

        createStudentButton.setText("Create Student");
        createStudentButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createStudentButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout newStudentPanelLayout = new javax.swing.GroupLayout(newStudentPanel);
        newStudentPanel.setLayout(newStudentPanelLayout);
        newStudentPanelLayout.setHorizontalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addGap(126, 126, 126)
                .addComponent(newStudentInfoLabel)
                .addGap(91, 91, 91))
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(newStudentGpaField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newStudentIdField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newStudentNameField, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(newStudentNeededField, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE)
                        .addComponent(newStudentEarnedField))
                    .addComponent(createStudentButton))
                .addGap(83, 83, 83))
        );
        newStudentPanelLayout.setVerticalGroup(
            newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(newStudentPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newStudentInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudentEarnedField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newStudentNeededField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(newStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newStudentGpaField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(createStudentButton))
                .addContainerGap(87, Short.MAX_VALUE))
        );

        mainPanel.add(newStudentPanel, "newStudentPanel");

        loadStudentInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        loadStudentInfoLabel.setText("Enter student ID");

        loadButton.setText("Load");

        javax.swing.GroupLayout loadStudentPanelLayout = new javax.swing.GroupLayout(loadStudentPanel);
        loadStudentPanel.setLayout(loadStudentPanelLayout);
        loadStudentPanelLayout.setHorizontalGroup(
            loadStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, loadStudentPanelLayout.createSequentialGroup()
                .addContainerGap(156, Short.MAX_VALUE)
                .addGroup(loadStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(loadStudentInfoLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(loadStudentIdField)
                    .addComponent(loadButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(166, 166, 166))
        );
        loadStudentPanelLayout.setVerticalGroup(
            loadStudentPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(loadStudentPanelLayout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(loadStudentInfoLabel)
                .addGap(18, 18, 18)
                .addComponent(loadStudentIdField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(loadButton)
                .addContainerGap(102, Short.MAX_VALUE))
        );

        mainPanel.add(loadStudentPanel, "loadStudentPanel");

        mainCoursePanel.setName(""); // NOI18N

        viewCoursesButton.setText("View Courses");
        viewCoursesButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewCoursesButtonActionPerformed(evt);
            }
        });

        addCourseButton.setText("Add Course");
        addCourseButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCourseButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout mainCoursePanelLayout = new javax.swing.GroupLayout(mainCoursePanel);
        mainCoursePanel.setLayout(mainCoursePanelLayout);
        mainCoursePanelLayout.setHorizontalGroup(
            mainCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainCoursePanelLayout.createSequentialGroup()
                .addGap(150, 150, 150)
                .addGroup(mainCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(viewCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(155, Short.MAX_VALUE))
        );
        mainCoursePanelLayout.setVerticalGroup(
            mainCoursePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, mainCoursePanelLayout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addComponent(viewCoursesButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addCourseButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(98, 98, 98))
        );

        mainPanel.add(mainCoursePanel, "mainCoursePanel");

        newCourseInfoLabel.setText("Enter course information");

        newCourseNameField.setText("Name");
        newCourseNameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseNameFieldFocusGained(evt);
            }
        });
        newCourseNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseNameFieldActionPerformed(evt);
            }
        });

        newCoursePrefixField.setText("Prefix");
        newCoursePrefixField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCoursePrefixFieldFocusGained(evt);
            }
        });
        newCoursePrefixField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCoursePrefixFieldActionPerformed(evt);
            }
        });

        newCourseCodeField.setText("Code");
        newCourseCodeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseCodeFieldFocusGained(evt);
            }
        });
        newCourseCodeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseCodeFieldActionPerformed(evt);
            }
        });

        newCourseStartField.setText("Start Date (mm, yyyy)");
        newCourseStartField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseStartFieldFocusGained(evt);
            }
        });

        newCourseEndField.setText("End Date (mm, yyyy)");
        newCourseEndField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseEndFieldFocusGained(evt);
            }
        });

        newCourseGradeField.setText("Grade");
        newCourseGradeField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseGradeFieldFocusGained(evt);
            }
        });
        newCourseGradeField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseGradeFieldActionPerformed(evt);
            }
        });

        newCourseCreditsField.setText("Credits");
        newCourseCreditsField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                newCourseCreditsFieldFocusGained(evt);
            }
        });
        newCourseCreditsField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseCreditsFieldActionPerformed(evt);
            }
        });

        newCourseNextButton.setText("Next");
        newCourseNextButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newCourseNextButtonActionPerformed(evt);
            }
        });

        newCourseGradeCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Classic", "Pass Fail" }));

        newCourseFinishedCheck.setText("Course Finished");

        javax.swing.GroupLayout addCoursesPanelLayout = new javax.swing.GroupLayout(addCoursesPanel);
        addCoursesPanel.setLayout(addCoursesPanelLayout);
        addCoursesPanelLayout.setHorizontalGroup(
            addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addComponent(newCourseFinishedCheck)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(newCourseInfoLabel)
                            .addComponent(newCourseNextButton))
                        .addGap(131, 131, 131))
                    .addGroup(addCoursesPanelLayout.createSequentialGroup()
                        .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(newCourseCodeField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newCoursePrefixField, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(newCourseGradeCombo, 0, 100, Short.MAX_VALUE))
                            .addComponent(newCourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                        .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newCourseStartField)
                            .addComponent(newCourseEndField)
                            .addComponent(newCourseGradeField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(newCourseCreditsField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE))
                        .addGap(74, 74, 74))))
        );
        addCoursesPanelLayout.setVerticalGroup(
            addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addCoursesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(newCourseInfoLabel)
                .addGap(18, 18, 18)
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(newCourseStartField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseNameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newCoursePrefixField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseEndField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newCourseCodeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseGradeField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(addCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(newCourseCreditsField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newCourseGradeCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(newCourseFinishedCheck)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addComponent(newCourseNextButton)
                .addContainerGap())
        );

        mainPanel.add(addCoursesPanel, "addCoursesPanel");

        addCatagoryFinishButton.setText("Finish");
        addCatagoryFinishButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addCatagoryFinishButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addCatagoryPanelLayout = new javax.swing.GroupLayout(addCatagoryPanel);
        addCatagoryPanel.setLayout(addCatagoryPanelLayout);
        addCatagoryPanelLayout.setHorizontalGroup(
            addCatagoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCatagoryPanelLayout.createSequentialGroup()
                .addContainerGap(181, Short.MAX_VALUE)
                .addComponent(addCatagoryFinishButton)
                .addGap(162, 162, 162))
        );
        addCatagoryPanelLayout.setVerticalGroup(
            addCatagoryPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, addCatagoryPanelLayout.createSequentialGroup()
                .addContainerGap(195, Short.MAX_VALUE)
                .addComponent(addCatagoryFinishButton)
                .addContainerGap())
        );

        mainPanel.add(addCatagoryPanel, "addCatagoryPanel");

        viewCoursesPanel.setPreferredSize(new java.awt.Dimension(402, 229));
        viewCoursesPanel.setRequestFocusEnabled(false);

        javax.swing.GroupLayout viewCoursesPanelLayout = new javax.swing.GroupLayout(viewCoursesPanel);
        viewCoursesPanel.setLayout(viewCoursesPanelLayout);
        viewCoursesPanelLayout.setHorizontalGroup(
            viewCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 402, Short.MAX_VALUE)
        );
        viewCoursesPanelLayout.setVerticalGroup(
            viewCoursesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 229, Short.MAX_VALUE)
        );

        mainPanel.add(viewCoursesPanel, "viewCoursesPanel");

        studentCardButton.setText("Student");
        studentCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentCardButtonActionPerformed(evt);
            }
        });

        courseCardButton.setText("Courses");
        courseCardButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseCardButtonActionPerformed(evt);
            }
        });

        calculatorCardButton.setText("Calculator");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(studentCardButton)
                .addGap(86, 86, 86)
                .addComponent(courseCardButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 93, Short.MAX_VALUE)
                .addComponent(calculatorCardButton)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(286, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(studentCardButton)
                    .addComponent(courseCardButton)
                    .addComponent(calculatorCardButton))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(45, 45, 45)
                    .addComponent(mainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(46, Short.MAX_VALUE)))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void studentCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentCardButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "defaultPanel");
    }//GEN-LAST:event_studentCardButtonActionPerformed

    private void addStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addStudentButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "newStudentPanel");
    }//GEN-LAST:event_addStudentButtonActionPerformed

    private void loadStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loadStudentButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "loadStudentPanel");
    }//GEN-LAST:event_loadStudentButtonActionPerformed

    private void newStudentNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudentNameFieldActionPerformed

    private void newStudentIdFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newStudentIdFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newStudentIdFieldActionPerformed

    private void createStudentButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createStudentButtonActionPerformed
        newStudent = new Student(newStudentNameField.getText(),
            Integer.parseInt(newStudentIdField.getText()),
                Integer.parseInt(newStudentNeededField.getText()));
        
        newStudent.setCreditsEarned(Integer.parseInt(newStudentEarnedField.getText()));
        newStudent.setGpa(Double.parseDouble(newStudentGpaField.getText()));
        
        newStudentInfoLabel.setText("Student " + newStudent.getName() + 
                " was created");
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainCoursePanel");
        
        System.out.println(newStudent);
    }//GEN-LAST:event_createStudentButtonActionPerformed

    private void newStudentNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentNameFieldFocusGained
        newStudentNameField.setText("");
    }//GEN-LAST:event_newStudentNameFieldFocusGained

    private void newStudentIdFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentIdFieldFocusGained
        newStudentIdField.setText("");
    }//GEN-LAST:event_newStudentIdFieldFocusGained

    private void newStudentGpaFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentGpaFieldFocusGained
        newStudentGpaField.setText("");
    }//GEN-LAST:event_newStudentGpaFieldFocusGained

    private void newStudentEarnedFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentEarnedFieldFocusGained
        newStudentEarnedField.setText("");
    }//GEN-LAST:event_newStudentEarnedFieldFocusGained

    private void newStudentNeededFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newStudentNeededFieldFocusGained
        newStudentNeededField.setText("");
    }//GEN-LAST:event_newStudentNeededFieldFocusGained

    private void courseCardButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseCardButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "mainCoursePanel");
    }//GEN-LAST:event_courseCardButtonActionPerformed

    private void viewCoursesButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewCoursesButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "viewCoursesPanel");
    }//GEN-LAST:event_viewCoursesButtonActionPerformed

    private void addCourseButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCourseButtonActionPerformed
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addCoursesPanel");
    }//GEN-LAST:event_addCourseButtonActionPerformed

    private void newCourseNameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseNameFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseNameFieldFocusGained

    private void newCourseNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseNameFieldActionPerformed

    private void newCoursePrefixFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCoursePrefixFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCoursePrefixFieldFocusGained

    private void newCoursePrefixFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCoursePrefixFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCoursePrefixFieldActionPerformed

    private void newCourseCodeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseCodeFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseCodeFieldFocusGained

    private void newCourseStartFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseStartFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseStartFieldFocusGained

    private void newCourseEndFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseEndFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseEndFieldFocusGained

    private void newCourseNextButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseNextButtonActionPerformed
        Course newCourse = new Course(newCourseNameField.getText(),
            newCoursePrefixField.getText(), Integer.parseInt(newCourseCodeField.getText()),
                Integer.parseInt(newCourseCreditsField.getText()));
        
        String[] startDate = new String[2];
        startDate = newCourseStartField.getText().split(", ");
        Calendar start = Calendar.getInstance();
        start.set(Integer.parseInt(startDate[1]), Integer.parseInt(startDate[0]), 01);
        
        String[] endDate = new String[2];
        endDate = newCourseEndField.getText().split(", ");
        Calendar end = Calendar.getInstance();
        end.set(Integer.parseInt(startDate[1]), Integer.parseInt(startDate[0]), 01);
        
        int gradeType = 0;
        String gradeTypeChoice = (String) newCourseGradeCombo.getSelectedItem();
        if (gradeTypeChoice.equals("Classic"))
            gradeType = 0;
        else
            gradeType = 1;
        
        CourseOffering newCourseOffering = new CourseOffering(newCourse, start, end,
            Double.parseDouble(newCourseGradeField.getText()), gradeType,
                Integer.parseInt(newCourseCreditsField.getText()));
        
        newStudent.addCourse(newCourseOffering);
        System.out.println(newStudent.printArray());
        
        CardLayout card = (CardLayout)mainPanel.getLayout();
        card.show(mainPanel, "addCatagoryPanel");
        
    }//GEN-LAST:event_newCourseNextButtonActionPerformed

    private void newCourseCodeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseCodeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseCodeFieldActionPerformed

    private void newCourseGradeFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseGradeFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseGradeFieldFocusGained

    private void newCourseGradeFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseGradeFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseGradeFieldActionPerformed

    private void newCourseCreditsFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_newCourseCreditsFieldFocusGained
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseCreditsFieldFocusGained

    private void newCourseCreditsFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newCourseCreditsFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newCourseCreditsFieldActionPerformed

    private void addCatagoryFinishButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addCatagoryFinishButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addCatagoryFinishButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TrackerCardGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TrackerCardGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addCatagoryFinishButton;
    private javax.swing.JPanel addCatagoryPanel;
    private javax.swing.JButton addCourseButton;
    private javax.swing.JPanel addCoursesPanel;
    private javax.swing.JButton addStudentButton;
    private javax.swing.JButton calculatorCardButton;
    private javax.swing.JButton courseCardButton;
    private javax.swing.JButton createStudentButton;
    private javax.swing.JPanel defaultPanel;
    private javax.swing.JButton loadButton;
    private javax.swing.JButton loadStudentButton;
    private javax.swing.JTextField loadStudentIdField;
    private javax.swing.JLabel loadStudentInfoLabel;
    private javax.swing.JPanel loadStudentPanel;
    private javax.swing.JPanel mainCoursePanel;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JTextField newCourseCodeField;
    private javax.swing.JTextField newCourseCreditsField;
    private javax.swing.JTextField newCourseEndField;
    private javax.swing.JCheckBox newCourseFinishedCheck;
    private javax.swing.JComboBox<String> newCourseGradeCombo;
    private javax.swing.JTextField newCourseGradeField;
    private javax.swing.JLabel newCourseInfoLabel;
    private javax.swing.JTextField newCourseNameField;
    private javax.swing.JButton newCourseNextButton;
    private javax.swing.JTextField newCoursePrefixField;
    private javax.swing.JTextField newCourseStartField;
    private javax.swing.JTextField newStudentEarnedField;
    private javax.swing.JTextField newStudentGpaField;
    private javax.swing.JTextField newStudentIdField;
    private javax.swing.JLabel newStudentInfoLabel;
    private javax.swing.JTextField newStudentNameField;
    private javax.swing.JTextField newStudentNeededField;
    private javax.swing.JPanel newStudentPanel;
    private javax.swing.JButton studentCardButton;
    private javax.swing.JButton viewCoursesButton;
    private javax.swing.JPanel viewCoursesPanel;
    // End of variables declaration//GEN-END:variables
}
